### ISSUE TITLE
章节和目录对应

### ISSUE THREAD

**Issue by Qiny-dl** [itWangCode/AI-Drug-Discovery-Design#1]
您好，博主。感谢您的分享。python我有一些基础，比较困扰的是在 list 目录下当前 03 0 5 06 07 等 和您的目录安排不太能对得上，可否检查一下实际的上传文件，这样子便于学习 感谢您

**Comment by itWangCode** [comment]
您好，我目前还没有上传完美，之前是想到来了就写了，所以没有完全按照这个目录结构来的
[image: image.png]
这是目前最新的完整的结构

Qiny-dl ***@***.***> 于2024年10月11日周五 18:42写道：

**Comment by Qiny-dl** [comment]
期待您上传最新文档，感谢 感恩 ღ( ´･ᴗ･` )

**Comment by itWangCode** [comment]
后期我将不开源的状态了


Qiny-dl ***@***.***>于2024年10月11日 周五20:07写道：

**Comment by Qiny-dl** [comment]
好可惜 才发现的宝藏项目 准备踏实跟着学习

**Comment by itWangCode** [comment]
目前还是开源的，我下周上传完整

Qiny-dl ***@***.***>于2024年10月11日 周五20:29写道：

**Comment by Qiny-dl** [comment]
好的好的 我及时下载 跟着您学习
